project:
  type: website
  output-dir: docs

website:
  title: "Paulo Fagandini"
  navbar:
    left:
      - href: https://pfagandini.github.io
        text: Home
      - href: fagandini_cv.qmd
        text: Curriculum Vitae
      - href: fagandini_resume.qmd
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



